# Use an official Node.js runtime as the base image
FROM node:14-alpine

# Set the working directory
WORKDIR /app/proj_fpms/frontend

# Copy package.json and package-lock.json to the /app/proj_fpms/frontend directory in the container
COPY package*.json /app/proj_fpms/frontend/

# Install dependencies
RUN npm install

# Copy the rest of the frontend files
COPY . .

# Start the development server
CMD ["npm", "start"]
